name: login_test_task
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  retrofit: ^4.5.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_secure_storage: ^9.2.4
  freezed: ^2.5.7
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.8.0
  build_runner: ^2.0.0
  injectable_generator: ^2.2.0
  retrofit_generator: ^9.1.5

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
